---
driver:
  name: vagrant
  customize:
    memory: 2048
    audio: "none"

provisioner:
  name: puppet_apply
  manifests_path: examples
  ignore_spec_fixtures: true
  custom_facts:
    packagecloud_master_token: <%= ENV['PACKAGECLOUD_MASTER_TOKEN'] %>
    ipaas_rt_infra_build_version: "1.6"
    ipaas_frontend_build_version: "1.6"

transport:
  name: sftp

platforms:
  - name: centos-7.4

verifier:
  name: serverspec
  remote_exec: false
  extra_flags: '--require spec_helper -I spec/acceptance'

suites:
  - name: frontend
    provisioner:
      manifest: frontend.pp
    verifier:
      patterns:
        - 'spec/acceptance/frontend_spec.rb'
  - name: services
    provisioner:
      manifest: services.pp
    verifier:
      patterns:
        - 'spec/acceptance/services_spec.rb'
  - name: engine
    provisioner:
      manifest: engine.pp
    verifier:
      patterns:
        - 'spec/acceptance/engine_spec.rb'
